config/routes.rb
CrowdHealthData::Application.routes.draw do
  resources :user_sessions
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :specialties, only: :show do
    resources :departments, only: :show
    resources :providers, only: [:show] do
      resources :waiting_times, only: [:new, :create]
    end
  end
  root to: 'specialties#show'

  get "search/category", to: "search#category"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :department
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

end

app/models/waiting_time.rb
class WaitingTime < ActiveRecord::Base
  belongs_to :specialty
  belongs_to :provider
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end

  def specialty
    id = params[:specialty_id] || params[:id]
    @specialty ||= (Specialty.where(id: id).first || Specialty.first)
  end

  def load_categories
    @specialties = Specialty.all
    @department = @provider.department if @provider
    @providers = if @department
                   Provider.where(department: @department)
                 else
                   Provider.all
                 end
    @departments = Department.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/departments_controller.rb
class DepartmentsController < CategoriesController
  before_action :specialty, :department, :load_categories

  def show
  end

  private
  def department
    @department ||= Department.find(params[:id])
  end
end

app/controllers/providers_controller.rb
class ProvidersController < CategoriesController
  before_action :specialty, :provider, :load_categories

  def show
  end

  private
  def provider
    @provider ||= Provider.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def category
    redirect_to destination_path(params[:category])
  end

  private

  def destination_path(categories)
    @specialty = Specialty.find(categories["specialty_id"])
    @department = Department.find_by_id(categories["department_id"])
    @provider = Provider.find_by_id(categories["provider_id"])

    if @provider
      destination_path = specialty_provider_path(@specialty, @provider)
    elsif @department
      destination_path = specialty_department_path(@specialty, @department)
    else
      destination_path = specialty_path(@specialty)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < CategoriesController
  before_action :specialty, :load_categories

  def show
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  def create
    create! do |success, failure|
      success.html { redirect_back_or_to(:providers, notice: 'Registration successful') }
      failure.html { render action: :new and return }
    end
  end

  private

  def resource_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/waiting_times_controller.rb
class WaitingTimesController < InheritedResources::Base
  before_filter :require_login
  before_action :specialty, :provider

  def create
    create! do |success, failure|
      success.html { redirect_to specialty_provider_path(@specialty, @provider), notice: 'Gracias por tu Opinión!' }
      failure.html { render action: :new and return }
    end
  end

  private
  def provider
    @provider = Provider.find(params[:provider_id])
  end

  def resource_params
    params.permit(:when, :waiting, :specialty_id, :provider_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waiting_time_helper.rb
module WaitingTimeHelper
end

app/views/departments/show.html.erb
<div class="ContainerBg">
  <div class="quickStatsMonitor">
    <li class="redStatFigQuick">
    <h2>0.5 día</h2>

    </li>
    <li class="orangeGoldFigQuick">
    <h2>32 días</h2>

    </li>
    <small>¿Qué es esto?</small>
  </div>
  <div >
    <h2 class="leftCarat" ><strong>Cantidad de días de espera para<br /> otorgar consultas médicas </strong><br /> Respecto a la ley y a la opinión de la gente,<br /> ¿las mutualistas cumplen los plazos?
    </h2>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-10 margin_l30px">
        <div id="graph"><%= image_tag "graph.png", class: "map" %></div>
      </div>
      <br clear="all" />
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-10 margin_l30px">
        <div class="col-md-6 redBox">Lo recabado sobre las mutualistas <br />(<strong>NO</strong> cumplen con los plazos de Ley)</div>
        <div class="col-md-6 greenBox"> Lo recabado sobre las mutualistas <br />(<strong>SÍ</strong> cumplen con los plazos de Ley)
        </div>
        <br clear="all" />
        <div class="col-md-10 BrownBox">Opinión de la gente</div>
      </div>
    </div>
    <div class="col-lg-12 Opina"><a href="#">Opiná</a><br clear="all" /></div>
  </div>
</div>

app/views/providers/_opinion.html.erb
<div id="graph1" class="chart-block">
  <div class="chart-block-title"></div>
  <div class="chart-block-column text">
    <div class="chart-block-text">
      <div>Menos de 2 días</div>
      <div></div>
    </div>
    <div class="chart-block-text">
      <div>2 días</div>
      <div></div>
    </div>
    <div class="chart-block-text">
      <div>Más de 2 días</div>
      <div></div>
    </div>
  </div>
  <div class="chart-block-column chart"></div>
</div>

app/views/providers/show.html.erb
<!-- <h1 class="uppercase"><%= @provider.name %></h1> -->
<!-- <h3><%= @provider.full_name %></h3> -->
<!-- <h2>Information</h2> -->
<!-- <p><%= link_to 'Website', @provider.web %></p> -->
<!--  -->
<!-- Tiempos de Espera: -->
<!-- Medicina General: <%= @provider.wait_general %> -->
<!-- Pediatria: <%= @provider.wait_pediatrician %> -->
<!-- Ginecologia: <%= @provider.wait_gynecologist %> -->
<!-- Cirugia General: <%= @provider.wait_surgery %> -->


<div class="ContainerBg">
  <div class="quickStatsMonitor">
    <li class="redStatFigQuick">
    <h2>0.5 día</h2>

    </li>
    <li class="orangeGoldFigQuick">
    <h2>32 día</h2>

    </li>
    <small>¿Qué es esto?</small>
  </div>
  <div class="statsFigurRow">
    <h2 class="leftCarat" ><strong>¿Cuál es el plazo máximo para<br />
        recibir una consulta médica?</strong> </h2>
    <div class="row">
      <div class="col-lg-12 statsFigure">
        <div class="col-md-6">
          <li class="greenStatFig">
          <h2>2 <br />
            <span>día</span></h2>
          <h3>Lo publicado en la Ley</h3>
          </li>
          <p>Plazo máximo de espera para
          consulta externa desde la fecha
          de la solicitud.</p>
          <small>Promedio de tiempo de espera
            Constitución de la República Oriental
            del Uruguay </small> </div>
        <div class="col-md-6">
          <li class="redStatFig">
          <h2>2.5 <br />
            <span>día</span></h2>
          <h3>Lo publicado en la Ley</h3>
          </li>
          <p>Plazo máximo de espera para
          consulta externa desde la fecha
          de la solicitud.</p>
          <small>Promedio de tiempo de espera
            Constitución de la República Oriental
            del Uruguay </small> </div>
      </div>
    </div>
  </div>
  <div class="statsFigurRow">
    <h2 class="leftCarat" ><strong>¿Para vos los plazos de espera<br />
        fueron otros?</strong> </h2>
    <div class="row">
      <div class="col-lg-12 statsFigure">
        <div class="col-md-6">
          <li class="orangeGoldStatFig">
          <h2>18 <br />
            <span>día</span></h2>
          <h3>Lo que a la
            gente le pasó</h3>
          </li>
          <p>Plazo máximo de espera para
          consulta externa desde la fecha
          de la solicitud.</p>
          <small>Promedio de tiempo de espera
            Constitución de la República Oriental
            del Uruguay </small> </div>
        <div class="col-md-6">
          <li class="opinado">
          <h2>90 personas han opinado</h2>
          <%= image_tag "statsInfo.png" %>

          </li>
        </div>
      </div>
    </div>
  </div>
  <div class="row"><div class="col-lg-12 margin_l30px"><%= image_tag "graph1.png" %> </div></div>
    <div class="row"><div class="col-lg-12 Opina">

    <%= link_to 'Opina', new_specialty_provider_waiting_time_path(@specialty.id, @provider.id) %>
      <br clear="all" /></div>

app/views/specialties/show.html.erb
<div>
  <h2 class="leftCarat" ><strong>Cantidad de días de espera para<br /> otorgar consultas médicas </strong><br /> Respecto a la ley, ¿qué departamento<br /> cumple los plazos?</h2>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="col-md-7 margin_l30px">
      <div id="map"><%= image_tag "map.png", class: "map" %></div>
      <h3 class="Que">¿Que opiná la gente sobre estos plazos?</h3>
    </div>
    <div class="col-md-4">
      <ul class="mapStats">
        <li class="redLable">
        <p>Departamento donde en promedio, lo recabado sobre las mutualistas, constata que <strong>NO</strong> se cumplieron con los plazos de Ley para otorgar consulas médicas </p>
        </li>
        <li class="greenLable">
        <p>Departamento donde en promedio, lo recabado sobre las mutualistas, constata que <strong>SÍ</strong> se  cumplieron con los plazos de Ley para otorgar consulas médicas
        </p>
        </li>
      </ul>
    </div>
  </div>
  <!-- <div class="col&#45;lg&#45;12 Opina"><a href="#">Opiná</a><br clear="all" /></div> -->
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <fieldset>
  <div class="form-group">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="form-group">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
</fieldset>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="form-group">
       <%= f.label :password %><br />
       <%= f.password_field :password %>
    </div>
    <div class="form-group">
       <%= f.label :password_confirmation %><br />
       <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/waiting_times/_form.html.erb
<%= form_tag specialty_provider_waiting_times_path, :method => :post do %>
  <%#= hidden_field_tag :specialty_id, value: "#{@specialty.id}" %>
  <fieldset>
    <div class="form-group">
      <%= label_tag 'Waiting time (in days)' %><br />
      <%= text_field_tag :waiting, nil, class: "form-control bfh-number", type: "number" %>
    </div>
    <div class="form-group">
      <%= label_tag 'When did you asked this appointment?' %><br />
      <%= text_field_tag :when, nil, class: "form-control bfh-datepicker", data: {format: "d-m-y", date: "today"}, type: "date" %>
    </div>

    <div class="form-group">
    <%= submit_tag 'Opina', class: "btn btn-default" %>
    </div>
  </fieldset>
<% end %>

app/views/waiting_times/new.html.erb
<h1><%= "Tiempo de Espera para #{@specialty.name} en #{@provider.name}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>