config/routes.rb
CrowdHealthData::Application.routes.draw do
  resources :user_sessions
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :specialties, only: :show do
    resources :departments, only: :show
    resources :providers, only: [:show] do
      resources :waiting_times, only: [:new, :create]
    end
  end
  root to: 'specialties#show'

  get "search/category", to: "search#category"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :department
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

end

app/models/waiting_time.rb
class WaitingTime < ActiveRecord::Base
  belongs_to :specialty
  belongs_to :provider
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end

  def specialty
    id = params[:specialty_id] || params[:id]
    @specialty ||= (Specialty.where(id: id).first || Specialty.first)
  end

  def load_categories
    @specialties = Specialty.all
    @department = @provider.department if @provider
    @providers = if @department
                   Provider.where(department: @department)
                 else
                   Provider.all
                 end
    @departments = Department.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/departments_controller.rb
class DepartmentsController < CategoriesController
  before_action :specialty, :department, :load_categories

  def show
  end

  private
  def department
    @department ||= Department.find(params[:id])
  end
end

app/controllers/providers_controller.rb
class ProvidersController < CategoriesController
  before_action :specialty, :provider, :load_categories

  def show
  end

  private
  def provider
    @provider ||= Provider.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def category
    redirect_to destination_path(params[:category])
  end

  private

  def destination_path(categories)
    @specialty = Specialty.find(categories["specialty_id"])
    @department = Department.find_by_id(categories["department_id"])
    @provider = Provider.find_by_id(categories["provider_id"])

    if @provider
      destination_path = specialty_provider_path(@specialty, @provider)
    elsif @department
      destination_path = specialty_department_path(@specialty, @department)
    else
      destination_path = specialty_path(@specialty)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < CategoriesController
  before_action :specialty, :load_categories

  def show
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  def create
    create! do |success, failure|
      success.html { redirect_back_or_to(:providers, notice: 'Registration successful') }
      failure.html { render action: :new and return }
    end
  end

  private

  def resource_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waiting_time_helper.rb
module WaitingTimeHelper
end

app/views/layouts/_categories_nav.html.erb
  <%= form_tag search_category_path, id: "categories", method: :get do %>
      <%= select_tag 'category[specialty_id]', options_from_collection_for_select(@specialties, :id, :name, @specialty.try(:id)), class: "selectpicker" %>
      <%= select_tag 'category[department_id]', options_from_collection_for_select(@departments, :id, :name, @department.try(:id)), prompt: "Departamento" %>
      <%= select_tag 'category[provider_id]', options_from_collection_for_select(@providers, :id, :name, @provider.try(:id)), prompt: "Mutualista" %>
  <% end %>

app/views/layouts/_navbar.html.erb
<div class="header">
  <% if current_user %>
    <button class="btn btn-default navbar-btn Headnav"><%= link_to "Perfil", edit_user_path(current_user.id) %></button>
    <button class="btn btn-default navbar-btn Headnav"><%= link_to "Salir", :logout, method: :post %></button>
  <% else %>
    <button class="btn btn-default navbar-btn Headnav"><%= link_to "Registro", new_user_path %></button>
    <button class="btn btn-default navbar-btn Headnav"><%= link_to "Login", :login %></button>
  <% end %>
  <button type="button" class="btn btn-default navbar-btn Headnav">Contacto</button>
  <button type="button" class="btn btn-default navbar-btn Headnav">Propósito</button>
  <button type="button" class="btn btn-default navbar-btn Headnav"><%= link_to 'Inicio', root_path %></button>
  <h1><%= link_to 'SaluDatos', root_path %></h1>

  <br clear="all" />
</div>
<!-- <div class="ContainerBg"> -->
  <!-- <div> -->
    <!-- <div class="btn&#45;group"> -->
      <!-- <button data&#45;toggle="dropdown" class="btn dropdown&#45;toggle selected">Departamento <span class="caret"></span></button> -->
      <!-- <ul class="dropdown&#45;menu"> -->
      <!-- </ul> -->
    <!--   <ul class="dropdown&#45;menu"> -->
    <!--     <li><a href="#">Action</a></li> -->
    <!--     <li><a href="#">Another action</a></li> -->
    <!--     <li class="divider"></li> -->
    <!--     <li><a href="#">Separated link</a></li> -->
    <!--   </ul> -->
    <!-- </div> -->
    <!-- <div class="btn&#45;group"> -->
    <!--   <button data&#45;toggle="dropdown" class="btn dropdown&#45;toggle selected">Mutualista  <span class="caret"></span></button> -->
    <!--   <ul class="dropdown&#45;menu"> -->
    <!--     <li><a href="#">Action</a></li> -->
    <!--     <li><a href="#">Another action</a></li> -->
    <!--     <li class="divider"></li> -->
    <!--     <li><a href="#">Separated link</a></li> -->
    <!--   </ul> -->
    <!-- </div> -->
    <!-- <div class="btn&#45;group"> -->
    <!--   <button data&#45;toggle="dropdown" class="btn dropdown&#45;toggle">Tiempo <span class="caret"></span></button> -->
    <!-- </div> -->
    <!-- <div class="btn&#45;group"> -->
    <!--   <button data&#45;toggle="dropdown" class="btn dropdown&#45;toggle">Cirugía General <span class="caret"></span></button> -->
    <!--   <ul class="dropdown&#45;menu"> -->
    <!--     <li><a href="#">Action</a></li> -->
    <!--     <li><a href="#">Another action</a></li> -->
    <!--     <li class="divider"></li> -->
    <!--     <li><a href="#">Separated link</a></li> -->
    <!--   </ul> -->
    <!-- </div> -->
  <!-- </div> -->
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaluDatos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta charset="utf-8"></meta>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"></meta>
  <meta content="width=device-width, initial-scale=1" name="viewport"></meta>
  <%= csrf_meta_tags %>
</head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 marginAuto">
        <%= render partial: 'layouts/navbar' %>
      <div>
        <% if flash[:notice] %>
        <p id="notice" class="alert alert-success"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
        <p id="alert" class="alert alert-danger"><%= flash[:alert] %></p>
        <% end %>
      </div>
      <%= content_for?(:categories) ? yield(:categories) : nil %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/categories.html.erb
<% content_for :categories do %>
  <%= render partial: 'layouts/categories_nav' %>
<% end %>
<%= render template: "layouts/application" %>